<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Emizentech\Priceslider\Block\FilterRenderer
 */
?>
<?php

?>
<?php if ($filter instanceof Magento\CatalogSearch\Model\Layer\Filter\Price): ?>
    <?php $range = $block->getPriceRange($filter); ?>
    <?php $url = $this->getFilterUrl($filter); ?>
    <script>
        var price_url = "<?php echo $url; ?>";
        require([
            'Magento_Catalog/js/price-utils',
            'jquery',
            "jquery/ui",
            'domReady!'
        ], function (priceUtils, $) {
            "use strict";
            $("#js-price-slider").slider({
                range: true,
                min: <?php echo $range['min']; ?>,
                max: <?php echo $range['max']; ?>,
                values: [ <?php echo $range['min']; ?>, <?php echo $range['max']; ?> ],
                slide: function (event, ui) {
                    $("#js-range-min").val(priceUtils.formatPrice(ui.values[0])+' <?php echo $block->getCurrentCurrencySymbol() ?>');
                    $("#js-range-max").val(priceUtils.formatPrice(ui.values[1])+' <?php echo $block->getCurrentCurrencySymbol() ?>');
                }
            });

            $('#js-price-slider-apply').click(function () {
                window.location.href = price_url + $("#js-price-slider").slider("values", 0) + "-" + $("#js-price-slider").slider("values", 1);
            });

            // Update the values for the min/max inputs
            $("#js-range-min").val(priceUtils.formatPrice($("#js-price-slider").slider("values", 0))+' <?php echo $block->getCurrentCurrencySymbol() ?>');
            $("#js-range-max").val(priceUtils.formatPrice($("#js-price-slider").slider("values", 1))+' <?php echo $block->getCurrentCurrencySymbol() ?>');
        });
    </script>
    <div id="js-price-slider"></div>
    <div class="range-wrapper" decimal-slider-attribute-unit="<?php echo $block->getCurrentCurrencySymbol() ?>">
        <input type="text" id="js-range-min" class="range" readonly>
        <div class="range-divider">-</div>
        <input type="text" id="js-range-max" class="range" readonly>
        <div id="js-price-slider-apply" class="action apply-range"><?php echo __('Apply'); ?></div>
    </div>
<?php else: ?>
    <ol class="items">
        <?php foreach ($filterItems as $filterItem): ?>
            <li class="my item">
                <?php if ($filterItem->getCount() > 0): ?>
                    <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                        <?php /* @escapeNotVerified */
                        echo $filterItem->getLabel() ?>
                        <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                            <span class="count"><?php /* @escapeNotVerified */
                                echo $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1): ?><?php /* @escapeNotVerified */
                                echo __('item') ?><?php else: ?><?php /* @escapeNotVerified */
                                echo __('items') ?><?php endif; ?></span></span>
                        <?php endif; ?>
                    </a>
                <?php else: ?>
                    <?php /* @escapeNotVerified */
                    echo $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?php /* @escapeNotVerified */
                            echo $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1): ?><?php /* @escapeNotVerified */
                            echo __('item') ?><?php else: ?><?php /* @escapeNotVerified */
                            echo __('items') ?><?php endif; ?></span></span>
                    <?php endif; ?>
                <?php endif; ?>
            </li>
        <?php endforeach ?>
    </ol>
<?php endif; ?>